program ablak4;                                            
uses crt;
begin
      textcolor(blue);
      textbackground(blue);
      clrscr;
      window(15,4,25,10);
       textbackground(white);
       clrscr;
       window(16,5,24,09);
       textbackground(blue);
       clrscr;
      window(15,13,25,19);
       textbackground(white);
       clrscr;
       window(16,14,24,18);
       textbackground(blue);
       clrscr;
      window(57,4,67,10);
       textbackground(white);
       clrscr;
       window(58,5,66,9);
       textbackground(blue);
       clrscr;
      window(57,13,67,19);
       textbackground(white);
       clrscr;
       window(58,14,66,18);
       textbackground(blue);
       clrscr;
      window(35,9,46,15);
       textbackground(white);
       clrscr;
       window(36,10,45,14);
       textbackground(blue);
       clrscr;
       gotoxy(3,3);
       textcolor(yellow);
       write('HELLO!');
       gotoxy(10,5);
      readln;
      clrscr;
end.








