
Program jatek;
   uses crt;
   var a,b,c:real;
  Begin
    clrscr;
    textbackground(0);
    clrscr;
    window(1,1,80,3);
    textbackground(4);
    textcolor(2);
    clrscr;
    write('               A FOX Laboratorium K‚sztete CC Carrma CC  ');
    window(1,24,80,25);
    textbackground(1);
    textcolor(0);
    clrscr;
    write('BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB');
    window(75,3,80,24);
    textbackground(10);
    clrscr;
    window(1,7,40,15);
    textbackground(11);
    textcolor(0);
    clrscr;
    write('');
    readln;
  End.




