program mezo1;
uses crt;
begin
   clrscr;
     writeln('#':1);
     writeln('#':3);

     writeln(1992:1);
     writeln(1992:4);
     writeln(1992:5);
     writeln(1992:7);
     writeln(-1992:1);
     writeln(-1992:3);
     writeln(-1992:5);
     writeln(-1992:7);
     writeln('Nyomj Enter-t!');
     readln;
   clrscr;
     writeln('hello':1);
     writeln('hello':3);
     writeln('hello':5);
     writeln('hello':7);

     writeln(true:1);
     writeln(true:3);
     writeln(true:5);
     writeln(true:7);
     writeln(false:1);
     writeln(false:3);
     writeln(false:5);
     writeln(false:7);
     writeln('Nyomj Enter-t!');
     readln;
   clrscr;
     writeln(123.456:1:1);
     writeln(123.456:1:3);
     writeln(123.456:1:4);
     writeln(123.456:5:1);
     writeln(123.456:6:1);
     writeln(123.456:7:1);

     writeln(-123.456:1:1);
     writeln(-123.456:1:3);
     writeln(-123.456:1:4);
     writeln(-123.456:5:1);
     writeln(-123.456:6:1);
     writeln(-123.456:7:1);

     writeln(567.8:1);
     writeln(567.8:8);
     writeln(567.8:9);
     writeln(567.8:10);
     writeln(567.8:11);

     writeln(-567.8:1);
     writeln(-567.8:8);
     writeln(-567.8:9);
     writeln(-567.8:10);
     writeln(-567.8:11);
     textcolor(red);
     writeln('N‚zd meg milyen form tumok hat s ra irta ki ¡gy!!');
     textcolor(lightgray);
     writeln('Nyomj Enter-t!');
     readln;
end.
